### ISSUE TITLE
this gem does not work in Rails 6.1 and above. 

### ISSUE THREAD

**Issue by drkaleem** [richpeck/exception_handler#100]
Error during failsafe response: undefined method `parent_name' for gchitt::Application:Class
  /usr/share/rvm/gems/ruby-3.0.0/gems/railties-6.1.3/lib/rails/railtie.rb:209:in `method_missing'
  /usr/share/rvm/gems/ruby-3.0.0/gems/exception_handler-0.8.0.0/app/views/layouts/exception.html.erb:6:in `__usr_share_rvm_gems_ruby_______gems_exception_handler_________app_views_layouts_exception_html_erb___2040302005256383136_67380'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/base.rb:247:in `public_send'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/base.rb:247:in `_run'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/template.rb:154:in `block in render'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/notifications.rb:205:in `instrument'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/template.rb:345:in `instrument_render_template'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/template.rb:152:in `render'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/renderer/template_renderer.rb:72:in `block in render_with_layout'

**Comment by drkaleem** [comment]
FYI. the issue is with the use of Rails.application.class.parent_name class. Starting Rails 6 its now Rails.application.class.module_parent_name

**Comment by richpeck** [comment]
I will fix this and push an update in about 1.5hrs

Thanks

**Comment by richpeck** [comment]
This was pushed with a new release (`0.8.0.1`).
