### ISSUE TITLE
Error during failsafe response: undefined method `respond_to' for ExceptionHandler::ExceptionController:Class

### ISSUE THREAD

**Issue by dbaker24** [richpeck/exception_handler#34]
Using Rails 5.0.0.beta3 I get that error... Error during failsafe response: undefined method `respond_to' for ExceptionHandler::ExceptionController:Class

Gemfile...
gem 'exception_handler', '~> 0.5.0'

Happens in both development and production.

**Comment by richpeck** [comment]
Can you try the latest version and let me know if the same issue occurs? We have it working with Rails 5.0.0.rc2 `gem 'exception_handler', '~> 0.5.1'`

**Comment by dbaker24** [comment]
Thanks for the quick response... The Gem looks great. Hope I can get it into service!

Just updated/restarted server(s) to 0.5.1 and it still hits me with the same error. 

Both instances I have, running locally OS X El Capitan and remote Ubuntu 14 server.

Here's a little more info...

  Message from application: undefined method `respond_to' for ExceptionHandler::ExceptionController:Class
Did you mean?  respond_to? (NoMethodError)
  /home/dbaker/.rvm/gems/ruby-2.3.0@xxx/gems/exception_handler-0.5.1/app/controllers/exception_handler/exception_controller.rb:6:in `<class:ExceptionController>'
  /home/dbaker/.rvm/gems/ruby-2.3.0@xxx/gems/exception_handler-0.5.1/app/controllers/exception_handler/exception_controller.rb:2:in `<module:ExceptionHandler>'
  /home/dbaker/.rvm/gems/ruby-2.3.0@xxx/gems/exception_handler-0.5.1/app/controllers/exception_handler/exception_controller.rb:1:in `<top (required)>'

**Comment by dbaker24** [comment]
Just checking to see if there are any updates on this issue. Thanks and Happy 4th of July!

**Comment by richpeck** [comment]
Thanks for the reply; the error should be resolved by adding the `responders` gem to your `Gemfile`:

```
#Gemfile 
gem 'responders', '~> 2.2'
```

https://github.com/plataformatec/responders

This just allows us to respond with the appropriate data for the `mime` type
